version: 1
disable_existing_loggers: False
formatters:
  # Txt
  default:
    (): 'uvicorn.logging.DefaultFormatter'
    fmt: '%(asctime)s %(levelprefix)-9s %(name)s -: %(message)s'
    use_colors: False
  # Json
  egib_default:
    (): 'pythonjsonlogger.jsonlogger.JsonFormatter'
    format: '%(asctime)s %(levelname)s %(name)s %(message)s'
  egib_access:
    (): 'backend.main.AccessJsonFormatter'
    format: '%(asctime)s %(levelname)s %(name)s %(client_addr)s %(request_line)s %(status_code)s %(user_agent)s'
handlers:
  # Txt
  console_default:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout
  # Json
  egib_default:
    class: logging.handlers.RotatingFileHandler
    formatter: egib_default
    filename: .logs/default.jsonl
    maxBytes: 5242880  # 5 MB max file size
    backupCount: 1  # Keep only one file (current + 1 backup)
  egib_access:
    class: logging.handlers.RotatingFileHandler
    formatter: egib_access
    filename: .logs/access.jsonl
    maxBytes: 5242880  # 5 MB max file size
    backupCount: 1  # Keep only one file (current + 1 backup)
  console_egib_default:
    class: logging.StreamHandler
    formatter: egib_default
    stream: ext://sys.stdout
  console_egib_access:
    class: logging.StreamHandler
    formatter: egib_access
    stream: ext://sys.stdout
loggers:
  # Txt
  uvicorn:
    level: INFO
    handlers:
      - console_default
  uvicorn.error:
    level: INFO
  uvicorn.access:  # disabled
    level: INFO
    propagate: False
  # Json
  egib_access:
    level: INFO
    propagate: False
    handlers:
      - egib_access
      - console_egib_access
  egib_default:
    level: INFO
    handlers:
      - egib_default
      - console_egib_default