repos:
  - repo: local
    hooks:
      - id: format-check
        name: Format-check
        language: system
        types: [python]
        entry: make -s format-check
        pass_filenames: false