services:
  backend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    volumes:
      - ./.logs:/app/.logs/
      - ./data/:/app/data/
    networks:
      - egib-prod-net
    ports:
      - "80:8000"
    environment:
      DEV: 0
networks:
    egib-prod-net: