services:
  backend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    volumes:
      - ./backend:/app/backend
      - ./.cache:/app/.cache/
      - ./.logs:/app/.logs/
      - ./data/:/app/data/
    networks:
      - egib-dev-net
    ports:
      - "8081:8000"
    environment:
      DEV: 1
networks:
    egib-dev-net: