services:
  db:
    restart: always
    image: "postgis/postgis:16-3.4"
    env_file:
      - .env
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    command: -p ${POSTGRES_PORT}
    networks:
      - egib-prod-net
    volumes:
      - ./.db:/var/lib/postgresql/data
  backend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    volumes:
      - ./.logs:/app/.logs/
      - ./data/:/app/data/
    networks:
      - egib-prod-net
    ports:
      - "80:8000"
    environment:
      DEV: 0
networks:
    egib-prod-net: